import { test } from 'node:test'

import { JAVA_CONDITION, javaImportEdges, scanJavaSource, translateUnicodeEscapes } from '@exodus/stasis-core/java'

// javaImportEdges' result as plain objects, its per-source-set Maps included.
const plain = (edges) => JSON.parse(JSON.stringify(edges, (_, v) => (v instanceof Map ? Object.fromEntries(v) : v)))
const edgesOf = (files) => plain(javaImportEdges(new Map(Object.entries(files))))

test('JAVA_CONDITION is the language tag the edges are keyed under', (t) => {
  t.assert.equal(JAVA_CONDITION, 'java')
})

test('scanJavaSource reads the package, imports, declared types and name chains', (t) => {
  const unit = scanJavaSource([
    '@Deprecated',
    'package com.lib;',
    'import com.lib.util.Strings;',
    'import com.lib.model.*;',
    'import static com.lib.Consts.MAX;',
    'import static com.lib.Other.*;',
    'import module java.base;',
    'public class Lib extends Base implements Api<Model> {',
    '  record Pair(int a, int b) {}',
    '  enum Mode { A }',
    '  @interface Marker {}',
    '  void f() { Helper.go(); Class<?> c = Foo.class; x().Bar.y(); com.lib.deep.Deep.run(); }',
    '}',
    'interface Secondary {}',
  ].join('\n'))
  t.assert.equal(unit.pkg, 'com.lib')
  t.assert.deepStrictEqual(unit.imports, [
    { segments: ['com', 'lib', 'util', 'Strings'], isStatic: false, onDemand: false },
    { segments: ['com', 'lib', 'model'], isStatic: false, onDemand: true },
    { segments: ['com', 'lib', 'Consts', 'MAX'], isStatic: true, onDemand: false },
    { segments: ['com', 'lib', 'Other'], isStatic: true, onDemand: true },
  ], 'a module import imports no type')
  t.assert.deepStrictEqual([...unit.types], ['Lib', 'Secondary'])
  t.assert.deepStrictEqual([...unit.declared], ['Lib', 'Pair', 'Mode', 'Marker', 'Secondary'])
  const refs = unit.refs.map((segments) => segments.join('.'))
  for (const ref of ['Deprecated', 'Base', 'Api', 'Model', 'Helper.go', 'Foo', 'com.lib.deep.Deep.run']) t.assert.ok(refs.includes(ref), ref)
  // `Foo.class` declares nothing, and `.Bar` after a call is a member, not a name.
  t.assert.ok(!unit.declared.has('Foo') && !refs.some((ref) => ref.startsWith('Bar')))
})

test('scanJavaSource reads no name in comments or literals', (t) => {
  const unit = scanJavaSource([
    'package p;',
    '/* import evil.InBlock; */',
    '// import evil.InLine;',
    'class A {',
    '  String s = "import evil.InString; \\" Quoted";',
    "  char c = '\\'';",
    '  String tb = """',
    '      class InTextBlock { Evil e; }',
    '      \\""" still the block """;',
    '  double d = 1.5e-3 + 0x1p-2 + 0x1e-2;',
    '  Real r;',
    '}',
  ].join('\n'))
  t.assert.deepStrictEqual(unit.imports, [])
  t.assert.deepStrictEqual([...unit.declared], ['A'])
  t.assert.deepStrictEqual(unit.refs.map((s) => s.join('.')).filter((r) => /^[A-Z]/u.test(r)), ['String', 'Real'])
})

test('unicode escapes are translated before lexing, as javac does', (t) => {
  t.assert.equal(translateUnicodeEscapes('a\\u0041 \\\\u0041 \\\\\\u0041 \\uuu0042 \\u00zz'), 'aA \\\\u0041 \\\\A B \\u00zz')
  // A `\u000a` ends a line comment: javac compiles the import after it.
  const unit = scanJavaSource('package p;\n// \\u000a import q.Smuggled;\nclass A {}\n')
  t.assert.deepStrictEqual(unit.imports, [{ segments: ['q', 'Smuggled'], isStatic: false, onDemand: false }])
  // An escaped backslash before it is no escape: the comment runs on.
  t.assert.deepStrictEqual(scanJavaSource('package p;\n// \\\\u000a import q.Smuggled;\nclass A {}\n').imports, [])
})

test('javaImportEdges resolves names as javac scopes them, to the declaring file', (t) => {
  const edges = edgesOf({
    'src/main/java/com/app/Main.java': [
      'package com.app;',
      'import com.app.util.Strings;',
      'import com.app.model.*;',
      'import static com.app.Consts.MAX;',
      'import static com.app.Flags.*;',
      'import com.app.Outer.Inner;',
      'import java.util.List;',
      'class Main {',
      '  Helper h;', // same package
      '  Model m;', // on-demand import
      '  com.app.deep.Deep d;', // fully qualified
      '  List<Strings> l;', // an external type: no edge
      '  R.string s; BuildConfig b;', // generated by the build, not here: no edge
      '  Secret x;', // declared in Holder.java, beside its public type
      '  com.app.Main self;', // its own type
      '}',
    ].join('\n'),
    'src/main/java/com/app/util/Strings.java': 'package com.app.util;\npublic class Strings {}\n',
    'src/main/java/com/app/model/Model.java': 'package com.app.model;\npublic class Model {}\n',
    'src/main/java/com/app/model/Unused.java': 'package com.app.model;\npublic class Unused {}\n',
    'src/main/java/com/app/Consts.java': 'package com.app;\nclass Consts { static int MAX; }\n',
    'src/main/java/com/app/Flags.java': 'package com.app;\nclass Flags {}\n',
    'src/main/java/com/app/Outer.java': 'package com.app;\nclass Outer { static class Inner {} }\n',
    'src/main/java/com/app/Helper.java': 'package com.app;\nclass Helper {}\n',
    'src/main/java/com/app/Holder.java': 'package com.app;\npublic class Holder {}\nclass Secret {}\n',
    'src/main/java/com/app/deep/Deep.java': 'package com.app.deep;\npublic class Deep {}\n',
  })
  const java = 'src/main/java/com/app'
  t.assert.deepStrictEqual(edges, {
    [`${java}/Main.java`]: {
      'com.app.util.Strings': `${java}/util/Strings.java`,
      'com.app.Consts': `${java}/Consts.java`,
      'com.app.Flags': `${java}/Flags.java`,
      'com.app.Outer': `${java}/Outer.java`, // a nested type is in its top-level type's file
      'com.app.Helper': `${java}/Helper.java`,
      'com.app.model.Model': `${java}/model/Model.java`,
      'com.app.deep.Deep': `${java}/deep/Deep.java`,
      'com.app.Secret': `${java}/Holder.java`,
    },
  })
})

test('javaImportEdges: a type the file declares or imports from elsewhere shadows its package\'s', (t) => {
  const edges = edgesOf({
    'a/A.java': 'package a;\nimport ext.Config;\nclass A { static class Node {} Config c; Node n; Other o; }\n',
    'a/Config.java': 'package a;\nclass Config {}\n',
    'a/Node.java': 'package a;\nclass Node {}\n',
    'a/Other.java': 'package a;\nclass Other {}\n',
  })
  t.assert.deepStrictEqual(edges, { 'a/A.java': { 'a.Other': 'a/Other.java' } })
})

test('javaImportEdges: the unnamed package, and a file away from its package\'s directory', (t) => {
  const edges = edgesOf({
    'Main.java': 'class Main { Util u; }\n',
    'Util.java': 'class Util { lib.Api a; }\n',
    'misc/Api.java': 'package lib;\npublic interface Api {}\n',
  })
  t.assert.deepStrictEqual(edges, { 'Main.java': { Util: 'Util.java' }, 'Util.java': { 'lib.Api': 'misc/Api.java' } })
})

test('javaImportEdges picks among copies of a type as Gradle compiles source sets', (t) => {
  const lib = 'node_modules/lib/android/src'
  const other = 'node_modules/other/android/src'
  const edges = edgesOf({
    // Main sees both architectures' spec: one edge to each.
    [`${lib}/main/java/com/lib/Module.java`]: 'package com.lib;\nclass Module extends Spec { Shared s; Dup d; }\n',
    [`${lib}/newarch/java/com/lib/Spec.java`]: 'package com.lib;\nclass Spec { Gen g; }\n',
    [`${lib}/oldarch/java/com/lib/Spec.java`]: 'package com.lib;\nclass Spec { Gen g; }\n',
    // Each spec sees its own set's Gen over the other set's, and main's Shared over a variant's.
    [`${lib}/newarch/java/com/lib/Gen.java`]: 'package com.lib;\nclass Gen { Shared s; }\n',
    [`${lib}/oldarch/java/com/lib/Gen.java`]: 'package com.lib;\nclass Gen { Shared s; }\n',
    [`${lib}/main/java/com/lib/Shared.java`]: 'package com.lib;\nclass Shared {}\n',
    [`${lib}/debug/java/com/lib/Shared.java`]: 'package com.lib;\nclass Shared {}\n',
    // A type two packages declare, neither in the asking module: one edge to each, keyed apart.
    [`${other}/main/java/com/lib/Dup.java`]: 'package com.lib;\nclass Dup {}\n',
    'node_modules/third/android/src/main/java/com/lib/Dup.java': 'package com.lib;\nclass Dup {}\n',
  })
  t.assert.deepStrictEqual(edges[`${lib}/main/java/com/lib/Module.java`], {
    'com.lib.Spec': { newarch: `${lib}/newarch/java/com/lib/Spec.java`, oldarch: `${lib}/oldarch/java/com/lib/Spec.java` },
    'com.lib.Shared': `${lib}/main/java/com/lib/Shared.java`,
    'com.lib.Dup': { main: `${other}/main/java/com/lib/Dup.java`, 'main#2': 'node_modules/third/android/src/main/java/com/lib/Dup.java' },
  })
  t.assert.deepStrictEqual(edges[`${lib}/newarch/java/com/lib/Spec.java`], { 'com.lib.Gen': `${lib}/newarch/java/com/lib/Gen.java` })
  t.assert.deepStrictEqual(edges[`${lib}/oldarch/java/com/lib/Spec.java`], { 'com.lib.Gen': `${lib}/oldarch/java/com/lib/Gen.java` })
  t.assert.deepStrictEqual(edges[`${lib}/oldarch/java/com/lib/Gen.java`], { 'com.lib.Shared': `${lib}/main/java/com/lib/Shared.java` })
})

test('javaImportEdges is the same whatever order the sources come in', (t) => {
  const files = Object.entries({
    'z/src/main/java/p/A.java': 'package p;\nclass A { B b; }\n',
    'a/src/main/java/p/B.java': 'package p;\nclass B {}\n',
    'm/src/main/java/p/B.java': 'package p;\nclass B {}\n',
  })
  const forward = plain(javaImportEdges(new Map(files)))
  t.assert.deepStrictEqual(plain(javaImportEdges(new Map(files.toReversed()))), forward)
  t.assert.deepStrictEqual(forward, { 'z/src/main/java/p/A.java': { 'p.B': { main: 'a/src/main/java/p/B.java', 'main#2': 'm/src/main/java/p/B.java' } } })
})
