import { test } from 'node:test'
import { posix } from 'node:path'

import { createVfsHost } from '../stasis/src/vfs-bundle.js'
import { PRISMA_VERSIONS, generatePrismaClients } from '../stasis/src/vfs-bundle/prisma.js'
import { caseVfs, cases, clientHash, isQueryCompiler, readHashes } from './prisma-generate.helper.js'

/* eslint-disable no-await-in-loop -- the cases are generated one at a time, each against its own hash */

// Every corpus case at every version, byte for byte against that Prisma's own `prisma generate`.

const hashes = readHashes()

test('the fixture holds every case, at every version stasis generates as', (t) => {
  t.assert.deepStrictEqual(Object.keys(hashes), PRISMA_VERSIONS)
  for (const version of PRISMA_VERSIONS) t.assert.deepStrictEqual(Object.keys(hashes[version]), Object.keys(cases))
})

// Edge-runtime cases, by the query compiler build and provider they carry.
const EDGE = { 'opt-workerd': ['fast', 'postgresql'], 'opt-cloudflare': ['fast', 'postgresql'], 'opt-vercel-edge': ['small', 'postgresql'], 'opt-edge-light': ['small', 'postgresql'], 'opt-sqlite-workerd': ['fast', 'sqlite'] }
// The generator's file header, which it puts above the copied bindings too.
const HEADER = '\n/* !!! This is code generated by Prisma. Do not edit directly. !!! */\n/* eslint-disable */\n// biome-ignore-all lint: generated file\n// @ts-nocheck \n'

for (const version of PRISMA_VERSIONS) {
  test(`--generate=prisma writes each case's client as Prisma ${version}'s prisma generate does`, async (t) => {
    for (const [name, c] of Object.entries(cases)) {
      const outputs = await generatePrismaClients({ host: createVfsHost(caseVfs(c, version)), root: '/', projects: new Set([c.cwd]) })
      t.assert.deepStrictEqual(outputs.map((output) => output.dir), [posix.join('/', c.output ?? 'generated')], name)
      const { files } = outputs[0]
      t.assert.equal(clientHash(files), hashes[version][name], `${name}, as Prisma ${version} writes it`)
      // The .wasm as shipped, the bindings under the header.
      const compiler = Object.fromEntries([...files].filter(([path]) => isQueryCompiler(path)).map(([path, bytes]) => [path, Buffer.from(bytes).toString()]))
      const [build, provider] = EDGE[name] ?? []
      t.assert.deepStrictEqual(compiler, build === undefined ? {} : {
        [`internal/query_compiler_${build}_bg.js`]: `${HEADER}stand-in query_compiler_${build}_bg.${provider}.mjs\n`,
        [`internal/query_compiler_${build}_bg.wasm`]: `stand-in query_compiler_${build}_bg.${provider}.wasm\n`,
      }, name)
    }
  })
}
