import { test } from 'node:test'
import { readFileSync } from 'node:fs'
import { join, posix } from 'node:path'

import { createVfsHost } from '../stasis/src/vfs-bundle.js'
import { PRISMA_VERSIONS, generatePrismaClients } from '../stasis/src/vfs-bundle/prisma.js'
import { caseVfs, cases, clientHash, isQueryCompiler } from './prisma-generate.helper.js'

/* eslint-disable no-await-in-loop -- the cases are generated one at a time, each against its own hash */

// The clients --generate=prisma writes (vfs-bundle/prisma.js), 7.10.0's generator's rewritten as
// each older Prisma writes them, against the hashes of what each Prisma's own `prisma generate`
// writes for the corpus (prisma-generate.helper.js): byte for byte, every case at every version.

const hashes = JSON.parse(readFileSync(join(import.meta.dirname, 'fixtures/prisma-generate.json'), 'utf8'))

test('the fixture holds every case, at every version stasis generates as', (t) => {
  t.assert.deepStrictEqual(Object.keys(hashes), PRISMA_VERSIONS)
  for (const version of PRISMA_VERSIONS) t.assert.deepStrictEqual(Object.keys(hashes[version]), Object.keys(cases))
})

const EDGE = { 'opt-workerd': 'fast_bg.postgresql', 'opt-cloudflare': 'fast_bg.postgresql', 'opt-vercel-edge': 'small_bg.postgresql', 'opt-edge-light': 'small_bg.postgresql', 'opt-sqlite-workerd': 'fast_bg.sqlite' }
// What the generator writes above the query compiler's bindings, as above each file it writes.
const HEADER = '\n/* !!! This is code generated by Prisma. Do not edit directly. !!! */\n/* eslint-disable */\n// biome-ignore-all lint: generated file\n// @ts-nocheck \n'

for (const version of PRISMA_VERSIONS) {
  test(`--generate=prisma writes each case's client as Prisma ${version}'s prisma generate does`, async (t) => {
    for (const [name, c] of Object.entries(cases)) {
      const outputs = await generatePrismaClients({ host: createVfsHost(caseVfs(c, version)), root: '/', projects: new Set([c.cwd]) })
      t.assert.deepStrictEqual(outputs.map((output) => output.dir), [posix.join('/', c.output ?? 'generated')], name)
      const { files } = outputs[0]
      t.assert.equal(clientHash(files), hashes[version][name], `${name}, as Prisma ${version} writes it`)
      // An edge runtime's client carries the query compiler the tree's prisma ships: its .wasm as it
      // is, and its bindings under the generator's header.
      const compiler = Object.fromEntries([...files].filter(([path]) => isQueryCompiler(path)).map(([path, bytes]) => [path, Buffer.from(bytes).toString()]))
      const which = EDGE[name]
      const build = which?.split('.')[0]
      t.assert.deepStrictEqual(compiler, which === undefined ? {} : {
        [`internal/query_compiler_${build}.js`]: `${HEADER}stand-in query_compiler_${which}.mjs\n`,
        [`internal/query_compiler_${build}.wasm`]: `stand-in query_compiler_${which}.wasm\n`,
      }, name)
    }
  })
}
